import type * as monaco from "monaco-editor";
import type { languages } from "monaco-editor";

// Completion provider for autocomplete suggestions
// Updated to match the new natural Scratch syntax (see SCRATCH_SYNTAX.md)
export const languageSelector = (monacoInstance: typeof monaco): languages.CompletionItemProvider => {
    return {
        provideCompletionItems: (model, position) => {
            const word = model.getWordUntilPosition(position);
            const range = {
                startLineNumber: position.lineNumber,
                startColumn: word.startColumn,
                endLineNumber: position.lineNumber,
                endColumn: word.endColumn,
            };
            
            const suggestions: languages.CompletionItem[] = [
                // ==================== VARIABLES & LISTS ====================
                {
                    label: "var (declare variable)",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "var ${1:myVar} = ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Declare a new variable with an initial value",
                    detail: "🟡 Variables: Declare",
                    range: range,
                },
                {
                    label: "list (declare list)",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "list ${1:myList} = []",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Declare a new list",
                    detail: "🟡 Lists: Declare",
                    range: range,
                },
                {
                    label: "set variable to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set ${1:myVar} to ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set a variable to a value",
                    detail: "🟡 Variables: Set",
                    range: range,
                },
                {
                    label: "change variable by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change ${1:myVar} by ${2:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change a variable by an amount",
                    detail: "🟡 Variables: Change",
                    range: range,
                },
                {
                    label: "show variable",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "show variable ${1:myVar}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Show variable on stage",
                    detail: "🟡 Variables: Show",
                    range: range,
                },
                {
                    label: "hide variable",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "hide variable ${1:myVar}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Hide variable from stage",
                    detail: "🟡 Variables: Hide",
                    range: range,
                },
                {
                    label: "add to list",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "add ${1:\"item\"} to ${2:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Add an item to a list",
                    detail: "🟡 Lists: Add",
                    range: range,
                },
                {
                    label: "delete of list",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "delete ${1:1} of ${2:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Delete item at index from list",
                    detail: "🟡 Lists: Delete",
                    range: range,
                },
                {
                    label: "delete all of list",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "delete all of ${1:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Delete all items from list",
                    detail: "🟡 Lists: Delete all",
                    range: range,
                },
                {
                    label: "insert at of list",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "insert ${1:\"item\"} at ${2:1} of ${3:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Insert item at position in list",
                    detail: "🟡 Lists: Insert",
                    range: range,
                },
                {
                    label: "replace item of list with",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "replace item ${1:1} of ${2:myList} with ${3:\"new\"}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Replace item at position in list",
                    detail: "🟡 Lists: Replace",
                    range: range,
                },
                {
                    label: "item of list",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "item ${1:1} of ${2:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get item at position in list",
                    detail: "🟡 Lists: Item",
                    range: range,
                },
                {
                    label: "length of list",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "length of ${1:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get number of items in list",
                    detail: "🟡 Lists: Length",
                    range: range,
                },
                {
                    label: "list contains",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "${1:myList} contains ${2:\"item\"}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if list contains item",
                    detail: "🟡 Lists: Contains",
                    range: range,
                },

                // ==================== EVENTS ====================
                {
                    label: "when green flag clicked",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when green flag clicked\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when the green flag is clicked",
                    detail: "🟡 Events: Start on flag click",
                    range: range,
                },
                {
                    label: "when key pressed",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when ${1|space,up arrow,down arrow,left arrow,right arrow,any,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9|} key pressed\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when a specific key is pressed. Use space, up arrow, etc.",
                    detail: "🟡 Events: Key press trigger",
                    range: range,
                },
                // Key constants for use in expressions and events
                {
                    label: "space",
                    kind: monacoInstance.languages.CompletionItemKind.Constant,
                    insertText: "space",
                    documentation: "Space key constant - use in 'when space key pressed'",
                    detail: "🟡 Events: Space key",
                    range: range,
                },
                {
                    label: "up arrow",
                    kind: monacoInstance.languages.CompletionItemKind.Constant,
                    insertText: "up arrow",
                    documentation: "Up arrow key constant - use in 'when up arrow key pressed'",
                    detail: "🟡 Events: Up arrow key",
                    range: range,
                },
                {
                    label: "down arrow",
                    kind: monacoInstance.languages.CompletionItemKind.Constant,
                    insertText: "down arrow",
                    documentation: "Down arrow key constant - use in 'when down arrow key pressed'",
                    detail: "🟡 Events: Down arrow key",
                    range: range,
                },
                {
                    label: "left arrow",
                    kind: monacoInstance.languages.CompletionItemKind.Constant,
                    insertText: "left arrow",
                    documentation: "Left arrow key constant - use in 'when left arrow key pressed'",
                    detail: "🟡 Events: Left arrow key",
                    range: range,
                },
                {
                    label: "right arrow",
                    kind: monacoInstance.languages.CompletionItemKind.Constant,
                    insertText: "right arrow",
                    documentation: "Right arrow key constant - use in 'when right arrow key pressed'",
                    detail: "🟡 Events: Right arrow key",
                    range: range,
                },
                {
                    label: "when this sprite clicked",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when this sprite clicked\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when this sprite is clicked",
                    detail: "🟡 Events: Sprite click trigger",
                    range: range,
                },
                {
                    label: "when backdrop switches to",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when backdrop switches to \"${1:backdrop1}\"\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when backdrop switches to a specific one",
                    detail: "🟡 Events: Backdrop switch trigger",
                    range: range,
                },
                {
                    label: "when timer > value",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when timer > ${1:10}\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when timer exceeds a value",
                    detail: "🟡 Events: Timer trigger",
                    range: range,
                },
                {
                    label: "when I receive message",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when I receive \"${1:message1}\"\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when a broadcast message is received",
                    detail: "🟡 Events: Message received",
                    range: range,
                },
                {
                    label: "when I start as a clone",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when I start as a clone\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when this sprite starts as a clone",
                    detail: "🟡 Events: Clone starts",
                    range: range,
                },
                {
                    label: "broadcast message",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "broadcast \"${1:message1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Send a broadcast message to all sprites",
                    detail: "🟡 Events: Send message",
                    range: range,
                },
                {
                    label: "broadcast message and wait",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "broadcast \"${1:message1}\" and wait",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Broadcast and wait for all receivers to finish",
                    detail: "🟡 Events: Broadcast and wait",
                    range: range,
                },

                // ==================== CONTROL ====================
                {
                    label: "wait seconds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "wait ${1:1} seconds",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Wait for a number of seconds",
                    detail: "🟠 Control: Wait",
                    range: range,
                },
                {
                    label: "repeat",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "repeat ${1:10}\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Repeat a block of code a number of times",
                    detail: "🟠 Control: Repeat loop",
                    range: range,
                },
                {
                    label: "forever",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "forever\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Repeat a block of code forever",
                    detail: "🟠 Control: Forever loop",
                    range: range,
                },
                {
                    label: "if then",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "if ${1:condition} then\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code if a condition is true",
                    detail: "🟠 Control: If statement",
                    range: range,
                },
                {
                    label: "if then else",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "if ${1:condition} then\n    ${2}\nelse\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code if condition is true, otherwise run else code",
                    detail: "🟠 Control: If-Else statement",
                    range: range,
                },
                {
                    label: "wait until",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "wait until ${1:condition}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Wait until a condition becomes true",
                    detail: "🟠 Control: Wait until",
                    range: range,
                },
                {
                    label: "repeat until",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "repeat until ${1:condition}\n    $0\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Repeat code until a condition becomes true",
                    detail: "🟠 Control: Repeat until",
                    range: range,
                },
                {
                    label: "stop all",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stop all",
                    documentation: "Stop all scripts in the project",
                    detail: "🟠 Control: Stop all",
                    range: range,
                },
                {
                    label: "stop this script",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stop this script",
                    documentation: "Stop this script",
                    detail: "🟠 Control: Stop this script",
                    range: range,
                },
                {
                    label: "stop other scripts in sprite",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stop other scripts in sprite",
                    documentation: "Stop other scripts in this sprite",
                    detail: "🟠 Control: Stop other scripts",
                    range: range,
                },
                {
                    label: "create clone of myself",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "create clone of myself",
                    documentation: "Create a clone of this sprite",
                    detail: "🟠 Control: Create clone of myself",
                    range: range,
                },
                {
                    label: "create clone of sprite",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "create clone of \"${1:Sprite1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Create a clone of a sprite",
                    detail: "🟠 Control: Create clone of sprite",
                    range: range,
                },
                {
                    label: "delete this clone",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "delete this clone",
                    documentation: "Delete this clone",
                    detail: "🟠 Control: Delete clone",
                    range: range,
                },

                // ==================== MOTION ====================
                {
                    label: "move steps",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "move ${1:10} steps",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Move the sprite forward by a number of steps",
                    detail: "🔵 Motion: Move steps",
                    range: range,
                },
                {
                    label: "turn right degrees",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "turn right ${1:15} degrees",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Turn the sprite clockwise by degrees",
                    detail: "🔵 Motion: Turn right",
                    range: range,
                },
                {
                    label: "turn left degrees",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "turn left ${1:15} degrees",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Turn the sprite counter-clockwise by degrees",
                    detail: "🔵 Motion: Turn left",
                    range: range,
                },
                {
                    label: "go to x y",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go to x: ${1:0} y: ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Go to specific x and y coordinates",
                    detail: "🔵 Motion: Go to x y",
                    range: range,
                },
                {
                    label: "go to mouse-pointer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go to mouse-pointer",
                    documentation: "Go to the mouse pointer position",
                    detail: "🔵 Motion: Go to mouse",
                    range: range,
                },
                {
                    label: "go to random position",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go to random position",
                    documentation: "Go to a random position on the stage",
                    detail: "🔵 Motion: Go to random",
                    range: range,
                },
                {
                    label: "go to sprite",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go to \"${1:Sprite1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Go to another sprite's position",
                    detail: "🔵 Motion: Go to sprite",
                    range: range,
                },
                {
                    label: "glide secs to x y",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "glide ${1:1} secs to x: ${2:0} y: ${3:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Glide to x y coordinates over seconds",
                    detail: "🔵 Motion: Glide to x y",
                    range: range,
                },
                {
                    label: "glide secs to mouse-pointer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "glide ${1:1} secs to mouse-pointer",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Glide to mouse pointer over seconds",
                    detail: "🔵 Motion: Glide to mouse",
                    range: range,
                },
                {
                    label: "glide secs to random position",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "glide ${1:1} secs to random position",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Glide to random position over seconds",
                    detail: "🔵 Motion: Glide to random",
                    range: range,
                },
                {
                    label: "point in direction",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "point in direction ${1:90}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Point the sprite in a direction (90=right, 0=up, -90=left, 180=down)",
                    detail: "🔵 Motion: Point direction",
                    range: range,
                },
                {
                    label: "point towards mouse-pointer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "point towards mouse-pointer",
                    documentation: "Point towards the mouse pointer",
                    detail: "🔵 Motion: Point towards mouse",
                    range: range,
                },
                {
                    label: "point towards sprite",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "point towards \"${1:Sprite1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Point towards another sprite",
                    detail: "🔵 Motion: Point towards sprite",
                    range: range,
                },
                {
                    label: "change x by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change x by ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change x position by an amount",
                    detail: "🔵 Motion: Change X",
                    range: range,
                },
                {
                    label: "set x to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set x to ${1:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set x position to a value",
                    detail: "🔵 Motion: Set X",
                    range: range,
                },
                {
                    label: "change y by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change y by ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change y position by an amount",
                    detail: "🔵 Motion: Change Y",
                    range: range,
                },
                {
                    label: "set y to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set y to ${1:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set y position to a value",
                    detail: "🔵 Motion: Set Y",
                    range: range,
                },
                {
                    label: "if on edge, bounce",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "if on edge, bounce",
                    documentation: "Bounce when touching the edge of the stage",
                    detail: "🔵 Motion: Bounce on edge",
                    range: range,
                },
                {
                    label: "set rotation style",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set rotation style ${1|left-right,all around,don't rotate|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set how the sprite rotates",
                    detail: "🔵 Motion: Rotation style",
                    range: range,
                },
                {
                    label: "x position",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "x position",
                    documentation: "Get the sprite's x position",
                    detail: "🔵 Motion: X position reporter",
                    range: range,
                },
                {
                    label: "y position",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "y position",
                    documentation: "Get the sprite's y position",
                    detail: "🔵 Motion: Y position reporter",
                    range: range,
                },
                {
                    label: "direction",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "direction",
                    documentation: "Get the sprite's direction",
                    detail: "🔵 Motion: Direction reporter",
                    range: range,
                },

                // ==================== LOOKS ====================
                {
                    label: "say text",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "say \"${1:Hello!}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a speech bubble with text",
                    detail: "🟣 Looks: Say",
                    range: range,
                },
                {
                    label: "say text for seconds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "say \"${1:Hello!}\" for ${2:2} seconds",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a speech bubble for a duration",
                    detail: "🟣 Looks: Say for seconds",
                    range: range,
                },
                {
                    label: "think text",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "think \"${1:Hmm...}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a thought bubble with text",
                    detail: "🟣 Looks: Think",
                    range: range,
                },
                {
                    label: "think text for seconds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "think \"${1:Hmm...}\" for ${2:2} seconds",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a thought bubble for a duration",
                    detail: "🟣 Looks: Think for seconds",
                    range: range,
                },
                {
                    label: "switch costume to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "switch costume to \"${1:costume1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Switch to a specific costume",
                    detail: "🟣 Looks: Switch costume",
                    range: range,
                },
                {
                    label: "next costume",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "next costume",
                    documentation: "Switch to the next costume",
                    detail: "🟣 Looks: Next costume",
                    range: range,
                },
                {
                    label: "switch backdrop to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "switch backdrop to \"${1:backdrop1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Switch to a specific backdrop",
                    detail: "🟣 Looks: Switch backdrop",
                    range: range,
                },
                {
                    label: "next backdrop",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "next backdrop",
                    documentation: "Switch to the next backdrop",
                    detail: "🟣 Looks: Next backdrop",
                    range: range,
                },
                {
                    label: "change size by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change size by ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change sprite size by a percentage",
                    detail: "🟣 Looks: Change size",
                    range: range,
                },
                {
                    label: "set size to %",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set size to ${1:100}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set sprite size to a percentage",
                    detail: "🟣 Looks: Set size",
                    range: range,
                },
                {
                    label: "change effect by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change ${1|color,fisheye,whirl,pixelate,mosaic,brightness,ghost|} effect by ${2:25}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change a graphic effect",
                    detail: "🟣 Looks: Change effect",
                    range: range,
                },
                {
                    label: "set effect to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set ${1|color,fisheye,whirl,pixelate,mosaic,brightness,ghost|} effect to ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set a graphic effect to a value",
                    detail: "🟣 Looks: Set effect",
                    range: range,
                },
                {
                    label: "clear graphic effects",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "clear graphic effects",
                    documentation: "Clear all graphic effects",
                    detail: "🟣 Looks: Clear effects",
                    range: range,
                },
                {
                    label: "show",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "show",
                    documentation: "Show the sprite",
                    detail: "🟣 Looks: Show",
                    range: range,
                },
                {
                    label: "hide",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "hide",
                    documentation: "Hide the sprite",
                    detail: "🟣 Looks: Hide",
                    range: range,
                },
                {
                    label: "go to front layer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go to front layer",
                    documentation: "Move sprite to front layer",
                    detail: "🟣 Looks: Go to front",
                    range: range,
                },
                {
                    label: "go to back layer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go to back layer",
                    documentation: "Move sprite to back layer",
                    detail: "🟣 Looks: Go to back",
                    range: range,
                },
                {
                    label: "go forward layers",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go forward ${1:1} layers",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Move sprite forward by layers",
                    detail: "🟣 Looks: Go forward layers",
                    range: range,
                },
                {
                    label: "go backward layers",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "go backward ${1:1} layers",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Move sprite backward by layers",
                    detail: "🟣 Looks: Go backward layers",
                    range: range,
                },
                {
                    label: "costume number",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "costume number",
                    documentation: "Get the current costume number",
                    detail: "🟣 Looks: Costume number reporter",
                    range: range,
                },
                {
                    label: "costume name",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "costume name",
                    documentation: "Get the current costume name",
                    detail: "🟣 Looks: Costume name reporter",
                    range: range,
                },
                {
                    label: "size",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "size",
                    documentation: "Get the sprite's size",
                    detail: "🟣 Looks: Size reporter",
                    range: range,
                },

                // ==================== SOUND ====================
                {
                    label: "play sound until done",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "play sound \"${1:meow}\" until done",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Play a sound and wait until it finishes",
                    detail: "🟢 Sound: Play until done",
                    range: range,
                },
                {
                    label: "start sound",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "start sound \"${1:meow}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Start playing a sound",
                    detail: "🟢 Sound: Start sound",
                    range: range,
                },
                {
                    label: "stop all sounds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stop all sounds",
                    documentation: "Stop all sounds",
                    detail: "🟢 Sound: Stop all",
                    range: range,
                },
                {
                    label: "change volume by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change volume by ${1:-10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change volume by an amount",
                    detail: "🟢 Sound: Change volume",
                    range: range,
                },
                {
                    label: "set volume to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set volume to ${1:100}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set volume to a percentage",
                    detail: "🟢 Sound: Set volume",
                    range: range,
                },
                {
                    label: "volume",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "volume",
                    documentation: "Get the current volume",
                    detail: "🟢 Sound: Volume reporter",
                    range: range,
                },

                // ==================== SENSING ====================
                {
                    label: "touching mouse-pointer",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "touching mouse-pointer",
                    documentation: "Check if touching the mouse pointer",
                    detail: "🔵 Sensing: Touching mouse",
                    range: range,
                },
                {
                    label: "touching edge",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "touching edge",
                    documentation: "Check if touching the edge",
                    detail: "🔵 Sensing: Touching edge",
                    range: range,
                },
                {
                    label: "touching sprite",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "touching \"${1:Sprite1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if touching another sprite",
                    detail: "🔵 Sensing: Touching sprite",
                    range: range,
                },
                {
                    label: "touching color",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "touching color \"${1:#FF0000}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if touching a color",
                    detail: "🔵 Sensing: Touching color",
                    range: range,
                },
                {
                    label: "key pressed",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "key ${1|space,up arrow,down arrow,left arrow,right arrow,any,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9|} pressed",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if a key is pressed",
                    detail: "🔵 Sensing: Key pressed",
                    range: range,
                },
                {
                    label: "mouse down",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "mouse down",
                    documentation: "Check if mouse button is down",
                    detail: "🔵 Sensing: Mouse down",
                    range: range,
                },
                {
                    label: "mouse x",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "mouse x",
                    documentation: "Get the mouse x position",
                    detail: "🔵 Sensing: Mouse X",
                    range: range,
                },
                {
                    label: "mouse y",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "mouse y",
                    documentation: "Get the mouse y position",
                    detail: "🔵 Sensing: Mouse Y",
                    range: range,
                },
                {
                    label: "ask and wait",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "ask \"${1:What's your name?}\" and wait",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Ask a question and wait for answer",
                    detail: "🔵 Sensing: Ask and wait",
                    range: range,
                },
                {
                    label: "answer",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "answer",
                    documentation: "Get the answer to the last ask",
                    detail: "🔵 Sensing: Answer reporter",
                    range: range,
                },
                {
                    label: "distance to mouse-pointer",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "distance to mouse-pointer",
                    documentation: "Get distance to mouse pointer",
                    detail: "🔵 Sensing: Distance to mouse",
                    range: range,
                },
                {
                    label: "distance to sprite",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "distance to \"${1:Sprite1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get distance to another sprite",
                    detail: "🔵 Sensing: Distance to sprite",
                    range: range,
                },
                {
                    label: "timer",
                    kind: monacoInstance.languages.CompletionItemKind.Value,
                    insertText: "timer",
                    documentation: "Get the timer value",
                    detail: "🔵 Sensing: Timer reporter",
                    range: range,
                },
                {
                    label: "reset timer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "reset timer",
                    documentation: "Reset the timer to 0",
                    detail: "🔵 Sensing: Reset timer",
                    range: range,
                },
                {
                    label: "set drag mode draggable",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set drag mode draggable",
                    documentation: "Allow sprite to be dragged",
                    detail: "🔵 Sensing: Set draggable",
                    range: range,
                },
                {
                    label: "set drag mode not draggable",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set drag mode not draggable",
                    documentation: "Prevent sprite from being dragged",
                    detail: "🔵 Sensing: Set not draggable",
                    range: range,
                },

                // ==================== OPERATORS ====================
                {
                    label: "pick random to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "pick random ${1:1} to ${2:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Pick a random number in range",
                    detail: "🟠 Operators: Random",
                    range: range,
                },
                {
                    label: "join strings",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "join \"${1:hello}\" \"${2:world}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Join two strings together",
                    detail: "🟠 Operators: Join",
                    range: range,
                },
                {
                    label: "letter of string",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "letter ${1:1} of \"${2:hello}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get a letter from a string",
                    detail: "🟠 Operators: Letter of",
                    range: range,
                },
                {
                    label: "length of string",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "length of \"${1:hello}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get the length of a string",
                    detail: "🟠 Operators: Length of",
                    range: range,
                },
                {
                    label: "string contains",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "\"${1:hello}\" contains \"${2:ell}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if string contains substring",
                    detail: "🟠 Operators: Contains",
                    range: range,
                },
                {
                    label: "mod",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "${1:a} mod ${2:b}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get remainder of division",
                    detail: "🟠 Operators: Modulo",
                    range: range,
                },
                {
                    label: "round",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "round ${1:3.5}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Round a number",
                    detail: "🟠 Operators: Round",
                    range: range,
                },
                {
                    label: "abs of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "abs of ${1:-5}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get absolute value",
                    detail: "🟠 Operators: Abs",
                    range: range,
                },
                {
                    label: "floor of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "floor of ${1:3.7}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Round down to integer",
                    detail: "🟠 Operators: Floor",
                    range: range,
                },
                {
                    label: "ceiling of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "ceiling of ${1:3.2}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Round up to integer",
                    detail: "🟠 Operators: Ceiling",
                    range: range,
                },
                {
                    label: "sqrt of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "sqrt of ${1:16}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get square root",
                    detail: "🟠 Operators: Sqrt",
                    range: range,
                },
                {
                    label: "sin of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "sin of ${1:90}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get sine of angle in degrees",
                    detail: "🟠 Operators: Sin",
                    range: range,
                },
                {
                    label: "cos of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "cos of ${1:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get cosine of angle in degrees",
                    detail: "🟠 Operators: Cos",
                    range: range,
                },
                {
                    label: "tan of",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "tan of ${1:45}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get tangent of angle in degrees",
                    detail: "🟠 Operators: Tan",
                    range: range,
                },
                {
                    label: "and",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "${1:condition1} and ${2:condition2}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Boolean AND",
                    detail: "🟠 Operators: And",
                    range: range,
                },
                {
                    label: "or",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "${1:condition1} or ${2:condition2}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Boolean OR",
                    detail: "🟠 Operators: Or",
                    range: range,
                },
                {
                    label: "not",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "not ${1:condition}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Boolean NOT",
                    detail: "🟠 Operators: Not",
                    range: range,
                },

                // ==================== MY BLOCKS ====================
                {
                    label: "define custom block",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "define ${1:myBlock} ${2:param1}\n    ${3:// code here}\nend",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Define a custom block (procedure)",
                    detail: "🔴 My Blocks: Define",
                    range: range,
                },
                {
                    label: "call custom block",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "call ${1:myBlock} ${2:value}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Call a custom block",
                    detail: "🔴 My Blocks: Call",
                    range: range,
                },

                // ==================== PEN (EXTENSION) ====================
                {
                    label: "pen down",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "pen down",
                    documentation: "Start drawing with the pen",
                    detail: "🟢 Pen: Pen down",
                    range: range,
                },
                {
                    label: "pen up",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "pen up",
                    documentation: "Stop drawing with the pen",
                    detail: "🟢 Pen: Pen up",
                    range: range,
                },
                {
                    label: "erase all",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "erase all",
                    documentation: "Erase all pen marks",
                    detail: "🟢 Pen: Erase all",
                    range: range,
                },
                {
                    label: "stamp",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stamp",
                    documentation: "Stamp the sprite's image",
                    detail: "🟢 Pen: Stamp",
                    range: range,
                },
                {
                    label: "set pen color to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set pen color to \"${1:#FF0000}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set the pen color",
                    detail: "🟢 Pen: Set color",
                    range: range,
                },
                {
                    label: "change pen size by",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change pen size by ${1:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change pen size",
                    detail: "🟢 Pen: Change size",
                    range: range,
                },
                {
                    label: "set pen size to",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set pen size to ${1:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set pen size",
                    detail: "🟢 Pen: Set size",
                    range: range,
                },
            ];

            return { suggestions };
        },
    };
};

// Hover provider for showing block documentation
export const hoverProvider = (monacoInstance: typeof monaco): languages.HoverProvider => {
    return {
        provideHover: (model, position) => {
            const word = model.getWordAtPosition(position);
            if (!word) return null;

            const hoverInfo: Record<string, string> = {
                // Events
                "when": "Event block - starts a script when something happens",
                "broadcast": "Send a message to all sprites",
                
                // Control
                "if": "Conditional statement - runs code if condition is true",
                "repeat": "Loop - repeats code a number of times",
                "forever": "Infinite loop - repeats code forever",
                "wait": "Pause execution for seconds",
                "stop": "Stop scripts from running",
                "clone": "Create or delete a clone of a sprite",
                
                // Motion
                "move": "Move the sprite forward by steps",
                "turn": "Rotate the sprite by degrees",
                "go": "Move to a position",
                "glide": "Smoothly move to a position",
                "point": "Set the sprite's direction",
                
                // Looks
                "say": "Display a speech bubble",
                "think": "Display a thought bubble",
                "switch": "Change costume or backdrop",
                "next": "Switch to next costume/backdrop",
                "show": "Make the sprite visible",
                "hide": "Make the sprite invisible",
                "set": "Set a value (position, variable, effect)",
                "change": "Change a value by an amount",
                
                // Variables
                "var": "Declare a new variable",
                "list": "Declare a new list",
                
                // Sensing
                "touching": "Check if touching something",
                "key": "Check if a key is pressed",
                "mouse": "Get mouse position or check if mouse is down",
                "ask": "Ask a question and wait for input",
                "answer": "Get the user's answer",
                "timer": "Get or reset the timer",
                "distance": "Get distance to something",
                
                // Operators
                "and": "Boolean AND - both conditions must be true",
                "or": "Boolean OR - at least one condition must be true",
                "not": "Boolean NOT - inverts the condition",
                "mod": "Modulo - remainder after division",
                "join": "Concatenate two strings",
                "round": "Round a number to nearest integer",
                
                // Pen
                "pen": "Pen drawing commands",
                "stamp": "Stamp the sprite's image on the stage",
                "erase": "Clear all pen marks",
                
                // Custom blocks
                "define": "Define a custom block (procedure)",
                "call": "Call a custom block",
            };

            const text = word.word.toLowerCase();
            if (hoverInfo[text]) {
                return {
                    contents: [
                        { value: `**${word.word}**` },
                        { value: hoverInfo[text] },
                    ],
                };
            }

            return null;
        },
    };
};
