import { languages } from "monaco-editor";
import * as monaco from "monaco-editor";

export const languageDef: languages.IMonarchLanguage = {
    tokenizer: {
        root: [
            // Comments
            [/\/\/.*$/, "comment"],

            // Events
            [/\b(when|flagClicked|keyPressed|spriteClicked|backdropSwitchesTo|loudnessGreaterThan|timerGreaterThan|messageReceived|broadcast|broadcastAndWait|cloneStarted)\b/, "keyword.scratch.event"],

            // Motion keywords
            [/\b(move|turn|goTo|glideTo|pointInDirection|pointTowards|changeX|setX|changeY|setY|bounceOnEdge|setRotationStyle)\b/, "keyword.scratch.motion"],

            // Looks keywords
            [/\b(say|think|switchCostumeTo|nextCostume|switchBackdropTo|nextBackdrop|changeSizeBy|setSizeTo|changeEffectBy|setEffectTo|clearEffects|show|hide|goToFrontBack|goForwardBackwardLayers)\b/, "keyword.scratch.looks"],

            // Sound keywords
            [/\b(playSound|playSoundUntilDone|stopAllSounds|changeVolumeBy|setVolumeTo|changePitchBy|setPitchTo)\b/, "keyword.scratch.sound"],

            // Control keywords
            [/\b(wait|repeat|forever|if|else|waitUntil|repeatUntil|stop|createClone|deleteThisClone)\b/, "keyword.scratch.control"],

            // Sensing keywords
            [/\b(touching|touchingColor|colorIsTouching|distanceTo|askAndWait|answer|keyDown|mouseDown|mouseX|mouseY|loudness|timer|resetTimer|current|daysSince2000|username)\b/, "keyword.scratch.sensing"],

            // Variables and Lists
            [/\b(var|list|set|change|showVariable|hideVariable|add|delete|deleteAll|insert|replace|itemOf|itemNumberOf|lengthOf|contains|showList|hideList)\b/, "keyword.scratch.variables"],

            // Operators keywords
            [/\b(and|or|not|join|letterOf|random|round|abs|floor|ceiling|sqrt|sin|cos|tan|asin|acos|atan|ln|log|ePowerOf|tenPowerOf|mod)\b/, "keyword.scratch.operators"],

            // Custom blocks
            [/\b(define)\b/, "keyword.scratch.custom"],

            // Boolean/special values
            [/\b(true|false|left|right|up|down|space|any|all|this|edge|mouse|myself|random)\b/, "constant.scratch"],

            // Operators
            [/\+|\-|\*|\/|>|<|=|%/, "operators.scratch"],

            // Numbers
            [/\d+(\.\d+)?/, "number"],

            // Strings
            [/"([^"]*)"/, "string"],
            [/'([^']*)'/, "string"],

            // Identifiers (variable and list names)
            [/[a-zA-Z_][a-zA-Z0-9_]*/, "identifier"],

            // Parentheses and brackets
            [/\(|\)/, "delimiter.parenthesis"],
            [/\[|\]/, "delimiter.bracket"],

            // Whitespace (ignore)
            [/\s+/, "white"],
        ],
    },
};

export const languageSelector = (monacoInstance: typeof monaco): languages.CompletionItemProvider => {
    return {
        provideCompletionItems: (model, position) => {
            const word = model.getWordUntilPosition(position);
            const range = {
                startLineNumber: position.lineNumber,
                startColumn: word.startColumn,
                endLineNumber: position.lineNumber,
                endColumn: word.endColumn,
            };
            
            const suggestions: languages.CompletionItem[] = [
                // ========== EVENTS ==========
                {
                    label: "when flagClicked",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when flagClicked\n    ",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when the green flag is clicked",
                    detail: "Event: Start on flag click",
                    range: range,
                },
                {
                    label: "when keyPressed",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when keyPressed ${1|space,up,down,left,right,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,any|}\n    ",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when a specific key is pressed",
                    detail: "Event: Key press trigger",
                    range: range,
                },
                {
                    label: "when spriteClicked",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when spriteClicked\n    ",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when this sprite is clicked",
                    detail: "Event: Sprite click trigger",
                    range: range,
                },
                {
                    label: "when messageReceived",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when messageReceived \"${1:message}\"\n    ",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when a broadcast message is received",
                    detail: "Event: Message received",
                    range: range,
                },
                {
                    label: "when cloneStarted",
                    kind: monacoInstance.languages.CompletionItemKind.Event,
                    insertText: "when cloneStarted\n    ",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code when this sprite starts as a clone",
                    detail: "Event: Clone starts",
                    range: range,
                },
                {
                    label: "broadcast",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "broadcast \"${1:message}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Send a broadcast message to all sprites",
                    detail: "Event: Send message",
                    range: range,
                },
                {
                    label: "broadcastAndWait",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "broadcastAndWait \"${1:message}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Broadcast and wait for all receivers to finish",
                    detail: "Event: Send and wait",
                    range: range,
                },

                // ========== MOTION ==========
                {
                    label: "move",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "move ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Move the sprite forward by a number of steps",
                    detail: "Motion: Move steps",
                    range: range,
                },
                {
                    label: "turn right",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "turn right ${1:15}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Turn the sprite clockwise by degrees",
                    detail: "Motion: Turn right",
                    range: range,
                },
                {
                    label: "turn left",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "turn left ${1:15}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Turn the sprite counter-clockwise by degrees",
                    detail: "Motion: Turn left",
                    range: range,
                },
                {
                    label: "goTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "goTo ${1|random,mouse,x|} ${2:0} ${3:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Go to a position (random, mouse pointer, or x y coordinates)",
                    detail: "Motion: Go to position",
                    range: range,
                },
                {
                    label: "goTo x y",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "goTo x ${1:0} y ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Go to specific x and y coordinates",
                    detail: "Motion: Go to x y",
                    range: range,
                },
                {
                    label: "glideTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "glideTo ${1:1} x ${2:0} y ${3:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Glide to a position over a number of seconds",
                    detail: "Motion: Glide to position",
                    range: range,
                },
                {
                    label: "pointInDirection",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "pointInDirection ${1:90}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Point the sprite in a direction (90=right, 0=up, -90=left, 180=down)",
                    detail: "Motion: Point direction",
                    range: range,
                },
                {
                    label: "pointTowards",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "pointTowards ${1|mouse,random|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Point towards mouse pointer or another sprite",
                    detail: "Motion: Point towards",
                    range: range,
                },
                {
                    label: "changeX",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "changeX ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change x position by an amount",
                    detail: "Motion: Change X",
                    range: range,
                },
                {
                    label: "setX",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "setX ${1:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set x position to a value",
                    detail: "Motion: Set X",
                    range: range,
                },
                {
                    label: "changeY",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "changeY ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change y position by an amount",
                    detail: "Motion: Change Y",
                    range: range,
                },
                {
                    label: "setY",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "setY ${1:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set y position to a value",
                    detail: "Motion: Set Y",
                    range: range,
                },
                {
                    label: "bounceOnEdge",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "bounceOnEdge",
                    documentation: "Bounce when touching the edge of the stage",
                    detail: "Motion: Bounce on edge",
                    range: range,
                },
                {
                    label: "setRotationStyle",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "setRotationStyle ${1|left-right,all around,don't rotate|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set how the sprite rotates",
                    detail: "Motion: Rotation style",
                    range: range,
                },

                // ========== LOOKS ==========
                {
                    label: "say",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "say \"${1:Hello!}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a speech bubble with text",
                    detail: "Looks: Say text",
                    range: range,
                },
                {
                    label: "say for seconds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "say \"${1:Hello!}\" for ${2:2} seconds",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a speech bubble for a duration",
                    detail: "Looks: Say for seconds",
                    range: range,
                },
                {
                    label: "think",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "think \"${1:Hmm...}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a thought bubble with text",
                    detail: "Looks: Think text",
                    range: range,
                },
                {
                    label: "think for seconds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "think \"${1:Hmm...}\" for ${2:2} seconds",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Display a thought bubble for a duration",
                    detail: "Looks: Think for seconds",
                    range: range,
                },
                {
                    label: "switchCostumeTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "switchCostumeTo \"${1:costume1}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Switch to a specific costume",
                    detail: "Looks: Switch costume",
                    range: range,
                },
                {
                    label: "nextCostume",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "nextCostume",
                    documentation: "Switch to the next costume",
                    detail: "Looks: Next costume",
                    range: range,
                },
                {
                    label: "changeSizeBy",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "changeSizeBy ${1:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change sprite size by a percentage",
                    detail: "Looks: Change size",
                    range: range,
                },
                {
                    label: "setSizeTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "setSizeTo ${1:100}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set sprite size to a percentage",
                    detail: "Looks: Set size",
                    range: range,
                },
                {
                    label: "show",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "show",
                    documentation: "Make the sprite visible",
                    detail: "Looks: Show sprite",
                    range: range,
                },
                {
                    label: "hide",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "hide",
                    documentation: "Make the sprite invisible",
                    detail: "Looks: Hide sprite",
                    range: range,
                },
                {
                    label: "goToFrontBack",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "goToFrontBack ${1|front,back|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Move sprite to front or back layer",
                    detail: "Looks: Go to layer",
                    range: range,
                },
                {
                    label: "goForwardBackwardLayers",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "goForwardBackwardLayers ${1|forward,backward|} ${2:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Move sprite forward or backward layers",
                    detail: "Looks: Change layer",
                    range: range,
                },
                {
                    label: "changeEffectBy",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "changeEffectBy ${1|color,fisheye,whirl,pixelate,mosaic,brightness,ghost|} ${2:25}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change a graphic effect by an amount",
                    detail: "Looks: Change effect",
                    range: range,
                },
                {
                    label: "setEffectTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "setEffectTo ${1|color,fisheye,whirl,pixelate,mosaic,brightness,ghost|} ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set a graphic effect to a value",
                    detail: "Looks: Set effect",
                    range: range,
                },
                {
                    label: "clearEffects",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "clearEffects",
                    documentation: "Clear all graphic effects",
                    detail: "Looks: Clear effects",
                    range: range,
                },

                // ========== SOUND ==========
                {
                    label: "playSound",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "playSound \"${1:meow}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Start playing a sound",
                    detail: "Sound: Play sound",
                    range: range,
                },
                {
                    label: "playSoundUntilDone",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "playSoundUntilDone \"${1:meow}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Play a sound and wait until it finishes",
                    detail: "Sound: Play until done",
                    range: range,
                },
                {
                    label: "stopAllSounds",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stopAllSounds",
                    documentation: "Stop all currently playing sounds",
                    detail: "Sound: Stop all",
                    range: range,
                },
                {
                    label: "changeVolumeBy",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "changeVolumeBy ${1:-10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change volume by an amount",
                    detail: "Sound: Change volume",
                    range: range,
                },
                {
                    label: "setVolumeTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "setVolumeTo ${1:100}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set volume to a percentage",
                    detail: "Sound: Set volume",
                    range: range,
                },

                // ========== CONTROL ==========
                {
                    label: "wait",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "wait ${1:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Wait for a number of seconds",
                    detail: "Control: Wait seconds",
                    range: range,
                },
                {
                    label: "repeat",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "repeat ${1:10}\n    ${2:// code here}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Repeat a block of code a number of times",
                    detail: "Control: Repeat loop",
                    range: range,
                },
                {
                    label: "forever",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "forever\n    ${1:// code here}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Repeat a block of code forever",
                    detail: "Control: Forever loop",
                    range: range,
                },
                {
                    label: "if",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "if ${1:condition}\n    ${2:// then}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code if a condition is true",
                    detail: "Control: If statement",
                    range: range,
                },
                {
                    label: "if else",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "if ${1:condition}\n    ${2:// then}\nelse\n    ${3:// else}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Run code if condition is true, otherwise run else code",
                    detail: "Control: If-Else statement",
                    range: range,
                },
                {
                    label: "waitUntil",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "waitUntil ${1:condition}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Wait until a condition becomes true",
                    detail: "Control: Wait until",
                    range: range,
                },
                {
                    label: "repeatUntil",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "repeatUntil ${1:condition}\n    ${2:// code here}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Repeat code until a condition becomes true",
                    detail: "Control: Repeat until",
                    range: range,
                },
                {
                    label: "stop",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "stop ${1|all,this script,other scripts|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Stop scripts (all, this script, or other scripts)",
                    detail: "Control: Stop",
                    range: range,
                },
                {
                    label: "createClone",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "createClone ${1|myself|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Create a clone of this sprite",
                    detail: "Control: Create clone",
                    range: range,
                },
                {
                    label: "deleteThisClone",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "deleteThisClone",
                    documentation: "Delete this clone",
                    detail: "Control: Delete clone",
                    range: range,
                },

                // ========== SENSING ==========
                {
                    label: "touching",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "touching ${1|edge,mouse,sprite|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if sprite is touching something",
                    detail: "Sensing: Touching?",
                    range: range,
                },
                {
                    label: "touchingColor",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "touchingColor \"${1:#ff0000}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if sprite is touching a color",
                    detail: "Sensing: Touching color?",
                    range: range,
                },
                {
                    label: "distanceTo",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "distanceTo ${1|mouse,sprite|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get distance to mouse or sprite",
                    detail: "Sensing: Distance to",
                    range: range,
                },
                {
                    label: "askAndWait",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "askAndWait \"${1:What's your name?}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Ask a question and wait for input",
                    detail: "Sensing: Ask and wait",
                    range: range,
                },
                {
                    label: "answer",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "answer",
                    documentation: "The answer from the last ask block",
                    detail: "Sensing: Answer value",
                    range: range,
                },
                {
                    label: "keyDown",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "keyDown ${1|space,up,down,left,right,any|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if a key is pressed",
                    detail: "Sensing: Key pressed?",
                    range: range,
                },
                {
                    label: "mouseDown",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "mouseDown",
                    documentation: "Check if mouse button is pressed",
                    detail: "Sensing: Mouse down?",
                    range: range,
                },
                {
                    label: "mouseX",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "mouseX",
                    documentation: "Get the mouse x position",
                    detail: "Sensing: Mouse X",
                    range: range,
                },
                {
                    label: "mouseY",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "mouseY",
                    documentation: "Get the mouse y position",
                    detail: "Sensing: Mouse Y",
                    range: range,
                },
                {
                    label: "timer",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "timer",
                    documentation: "Get the timer value in seconds",
                    detail: "Sensing: Timer",
                    range: range,
                },
                {
                    label: "resetTimer",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "resetTimer",
                    documentation: "Reset the timer to 0",
                    detail: "Sensing: Reset timer",
                    range: range,
                },
                {
                    label: "loudness",
                    kind: monacoInstance.languages.CompletionItemKind.Variable,
                    insertText: "loudness",
                    documentation: "Get the microphone loudness level",
                    detail: "Sensing: Loudness",
                    range: range,
                },
                {
                    label: "current",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "current ${1|year,month,date,day of week,hour,minute,second|}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get current date/time component",
                    detail: "Sensing: Current time",
                    range: range,
                },

                // ========== VARIABLES ==========
                {
                    label: "var",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "var ${1:myVar} = ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Declare a new variable",
                    detail: "Variables: Create variable",
                    range: range,
                },
                {
                    label: "set",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "set ${1:myVar} to ${2:0}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Set a variable to a value",
                    detail: "Variables: Set variable",
                    range: range,
                },
                {
                    label: "change",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "change ${1:myVar} by ${2:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Change a variable by an amount",
                    detail: "Variables: Change variable",
                    range: range,
                },
                {
                    label: "showVariable",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "showVariable ${1:myVar}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Show a variable monitor on stage",
                    detail: "Variables: Show variable",
                    range: range,
                },
                {
                    label: "hideVariable",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "hideVariable ${1:myVar}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Hide a variable monitor",
                    detail: "Variables: Hide variable",
                    range: range,
                },

                // ========== LISTS ==========
                {
                    label: "list",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "list ${1:myList} = []",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Declare a new list",
                    detail: "Lists: Create list",
                    range: range,
                },
                {
                    label: "add to list",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "add ${1:thing} to ${2:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Add an item to a list",
                    detail: "Lists: Add item",
                    range: range,
                },
                {
                    label: "delete from list",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "delete ${1:1} of ${2:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Delete an item from a list",
                    detail: "Lists: Delete item",
                    range: range,
                },
                {
                    label: "deleteAll",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "deleteAll of ${1:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Delete all items from a list",
                    detail: "Lists: Delete all",
                    range: range,
                },
                {
                    label: "insert at",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "insert ${1:thing} at ${2:1} of ${3:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Insert an item at a position in a list",
                    detail: "Lists: Insert item",
                    range: range,
                },
                {
                    label: "replace item",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "replace item ${1:1} of ${2:myList} with ${3:thing}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Replace an item in a list",
                    detail: "Lists: Replace item",
                    range: range,
                },
                {
                    label: "itemOf",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "itemOf ${1:myList} ${2:1}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get an item from a list by index",
                    detail: "Lists: Item of list",
                    range: range,
                },
                {
                    label: "itemNumberOf",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "itemNumberOf ${1:thing} in ${2:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get the index of an item in a list",
                    detail: "Lists: Item number",
                    range: range,
                },
                {
                    label: "lengthOf",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "lengthOf ${1:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get the length of a list",
                    detail: "Lists: Length of list",
                    range: range,
                },
                {
                    label: "contains",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "${1:myList} contains ${2:thing}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Check if a list contains an item",
                    detail: "Lists: Contains item?",
                    range: range,
                },
                {
                    label: "showList",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "showList ${1:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Show a list monitor on stage",
                    detail: "Lists: Show list",
                    range: range,
                },
                {
                    label: "hideList",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "hideList ${1:myList}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Hide a list monitor",
                    detail: "Lists: Hide list",
                    range: range,
                },

                // ========== OPERATORS ==========
                {
                    label: "random",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "random ${1:1} to ${2:10}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Pick a random number between two values",
                    detail: "Operators: Random number",
                    range: range,
                },
                {
                    label: "join",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "join \"${1:hello}\" \"${2:world}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Join two strings together",
                    detail: "Operators: Join strings",
                    range: range,
                },
                {
                    label: "letterOf",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "letterOf ${1:1} of \"${2:hello}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get a letter from a string",
                    detail: "Operators: Letter of string",
                    range: range,
                },
                {
                    label: "length of string",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "length of \"${1:hello}\"",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get the length of a string",
                    detail: "Operators: String length",
                    range: range,
                },
                {
                    label: "mod",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "${1:10} mod ${2:3}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get the remainder of division (modulo)",
                    detail: "Operators: Modulo",
                    range: range,
                },
                {
                    label: "round",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "round ${1:3.5}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Round a number to nearest integer",
                    detail: "Operators: Round",
                    range: range,
                },
                {
                    label: "abs",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "abs ${1:-5}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get absolute value of a number",
                    detail: "Operators: Absolute value",
                    range: range,
                },
                {
                    label: "floor",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "floor ${1:3.7}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Round down to nearest integer",
                    detail: "Operators: Floor",
                    range: range,
                },
                {
                    label: "ceiling",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "ceiling ${1:3.2}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Round up to nearest integer",
                    detail: "Operators: Ceiling",
                    range: range,
                },
                {
                    label: "sqrt",
                    kind: monacoInstance.languages.CompletionItemKind.Function,
                    insertText: "sqrt ${1:16}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Get the square root of a number",
                    detail: "Operators: Square root",
                    range: range,
                },
                {
                    label: "and",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "${1:condition1} and ${2:condition2}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Logical AND - true if both conditions are true",
                    detail: "Operators: And",
                    range: range,
                },
                {
                    label: "or",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "${1:condition1} or ${2:condition2}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Logical OR - true if either condition is true",
                    detail: "Operators: Or",
                    range: range,
                },
                {
                    label: "not",
                    kind: monacoInstance.languages.CompletionItemKind.Operator,
                    insertText: "not ${1:condition}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Logical NOT - inverts condition",
                    detail: "Operators: Not",
                    range: range,
                },

                // ========== CUSTOM BLOCKS ==========
                {
                    label: "define",
                    kind: monacoInstance.languages.CompletionItemKind.Keyword,
                    insertText: "define ${1:myBlock}\n    ${2:// block code}",
                    insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    documentation: "Define a custom block (function)",
                    detail: "Custom: Define block",
                    range: range,
                },
            ];

            return { suggestions: suggestions };
        },
    };
};

export const initialCode = `when flagClicked
    repeat 4
    move 10
    wait 1
`;
